### ISSUE TITLE
Get all Roles for a given group

### ISSUE THREAD

**Issue by DavidSichau** [alanning/meteor-roles#102]
Is there a way to get all Roles for a specific group? Like `Roles.getRolesForGroup("xyz")`

I would like to have this possibility as in my system I have different groups and group managers, which should add roles only for a specific group. The problem is that the roles are generated dynamically and therefore are not known until they are attached to a specific user.

So far the only solution with the existing roles packages is to loop over all users. However this is a very expensive operation and I want to avoid this..

One solution would be to extend the `Roles` collection and specify for each role in addition to the name an array of Groups where the roles is used. The one can run a query against the `Roles` Collection and get the result easy.

Or are there better solutions to achieve this behaviour?

**Comment by alanning** [comment]
Hi David,

I think your suggestion is right re: adding a mapping into the Roles collection.  Originally the whole purpose for having the Roles collection was to allow for easier UI stuff like this (technically the Roles collection isn't necessary).  

So, yes, adding a mapping of groups to a specific entry in the Roles collection sounds like the best solution.

**Comment by mitar** [comment]
So roles are currently independent from groups (or partitions in v2.0). You can assign any role to any group. If your app requires that only a subset of roles can be assigned to a particular group, you should assure that yourself. Because it is not even enough just to limit what is displayed to the user, you also have to assure that if a malicious user does not call `addUsersToRoles` with role which should not be assigned to a particular group, that call fails. The best way is to wrap `addUsersToRoles` into a Meteor method which does all necessary checks. You should not be calling `addUsersToRoles` directly anyway from the client.

How you store the information which roles can be assigned by which group in your app you can decide. You can probably more or less without any worry reuse `Meteor.roles` collection for that as well. The content of roles' documents is pretty thin anyway.

This feature is something you could develop an extra package and offer it to people who need it. But I do not believe it should be part of the core. (Because it is unclear how that relation between groups and allowed roles should be stored. Some apps might simply have that hard-coded.)
