### ISSUE TITLE
Question: Feasible to ensure index on users' roles field?

### ISSUE THREAD

**Issue by manybothans** [alanning/meteor-roles#105]
I'm writing an app that allows businesses to add multiple retail locations, with the ability to give other users access to certain admin functions by location. I'm using the name of each location as a Group, and either 'manager' or 'csr' as the Roles.

It would be useful to have frequent access to the `Roles.getUsersInRole` method to get a list of, say, all the users with manager privileges at a given location, but I understand this requires a full collection scan since by default there's no index on the users' roles field.

Would it be feasible for me to ensure a multikey index on the roles field myself? Or is there some deeper mongoDB issue I'm not aware of that would make such an index not advisable in this situation?

Thanks!

**Comment by alanning** [comment]
The limitation with MongoDB is only because I use the group name as an object key rather than a real limitation of the database itself.  If I'm understanding your setup correctly, this is how it would actually be structured in the database:

```
var roles = {
  "location1": ['manager', 'csr'],
  "location2": ['csr']
}
```

This structure is optimized for object access once the record has been retrieved but means you can't index the "groups".  The reason I did it this way is because in our app, we have a separate field that tracks what "groups" a users is a member of so we index that and only use the "roles" structure to determine permissions within a group.

I'd recommend having a separate field on the user object that tracks "membership" which you index, like we do.  The nice thing about it is that it keeps the membership independent of what permissions the user has so your users can do nice things like add someone to a "group" and then assign permissions later.  It also enables temporarily suspending certain permissions without loosing track of which groups the user is a member of.

**Comment by manybothans** [comment]
Ah good idea. Thanks!

**Comment by alanning** [comment]
Cool username by the way.  :-)

**Comment by manybothans** [comment]
Haha thanks! So excited for December :)

**Comment by mitar** [comment]
In v2.0 there is a different database schema used for groups (partitions) and there is an index automatically made on it. Closing this ticket in favor of that.
