### ISSUE TITLE
Roles.createRole simply not working.

### ISSUE THREAD

**Issue by vacarsu** [alanning/meteor-roles#107]
Hi, I'm trying to setup the roles. Currently I have one role named 'admin', however when I try to make any other role it simply doesn't work. I get no errors when trying to create them from the client, but when I try to create the from a server startup I get the following error, MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.roles.$userId_1  dup key: { : null }.

**Comment by alanning** [comment]
Hi @vacarsu, looks like you added an index to the "roles" collection that is preventing the insertion of duplicate user ids.  Does that sound feasible?  This package only adds one index, an index on the "name" field of the "roles" collection.

**Comment by vacarsu** [comment]
I assumed this as well, I used the meteor mongo CL to remove indexes and I still have the problem. If it helps I'm using Collection2.

**Comment by alanning** [comment]
Can you post an example app to a public repo for me to look at?  Otherwise, I'd suggest stripping it down to the minimal app that works and then adding pieces back until it stops working again.  Then you'll know which piece is causing the trouble.

One other issue I've heard before is that packages that modify internal Meteor collection objects mess things up somehow and that making sure the roles package comes before the collection package in the `.meteor/packages` file may help.

**Comment by vacarsu** [comment]
I'm using angular-meteor, could this be the problem? I'll put up an example project shortly, I've got it kind of working as I can create the roles from the startup, and set users to roles now. but I can't seem to add roles from the front end.

Basically, how I currently have this set up - I have a meteor method which is just the Roles.createRole() method, them I'm using the $meteor.call service to call that method and create the role. I'm doing the same thing for role deletion too.

**Comment by vacarsu** [comment]
Here is the repo. https://github.com/vacarsu/roles-example

**Comment by vacarsu** [comment]
I'm going to close this, as the main issue to this has been solved.

**Comment by alanning** [comment]
The issue is that the `Roles.createRole` call is always being passed
`null`.

Try changing the `addRole` Meteor method to this:

```
  addRole: function (role) {
    console.log("[addRole]", role)
  Roles.createRole(role);
  return 'success';
  },
```

Also, this is my first look at angular but man that seems a bit
complicated.  Have you tried just using straight Blaze?  You can still use
Polymer so the styling wouldn't have to change.

**Comment by vacarsu** [comment]
That worked! And yes angular looks pretty complicated but once you learn it it's pretty powerful. I will definitely look into blaze and polymer. Thanks for your help!

**Comment by thomasmery** [comment]
Hi there,

just a note to say I had the same pb


- cloned this repo
- 
just added `role` fr

**Comment by alanning** [comment]
@thomasmery, thanks for reporting this.  In your case, you are using the `v2.0` branch of roles which uses a different database schema structure.  Version 1 has an index on the 'name' field as I mentioned above.  In version 2, there is no 'name' field so MongoDB is interpreting the lack of a field as "undefined" and throwing the duplicate error due to there being more than one "undefined" name value.

So anyone using the `v2.0` branch with a database that already has data in it from `v1` will need to remove the index on `name` as you found.

I'll create a new v2 issue for this so we can track it and better help people make the transition.

**Comment by mitar** [comment]
This is then duplicate of #174.

**Comment by alanning** [comment]
Cool, then I won't create a new issue.

**Comment by thomasmery** [comment]
Many thanks!

I guess I did not search well enough
