### ISSUE TITLE
Shouldn't `Roles.getGroupsForUser` return all groups if the user belongs to GLOBAL_GROUP?

### ISSUE THREAD

**Issue by AlexFrazer** [alanning/meteor-roles#110]
Okay so I log my user.

```
> Meteor.user().roles
roles: {
  __global_roles__: [
    'internal'
  ]
}
```

However, in my publication, I want to publish data to all those whom belong to a group.

```
Meteor.publish('User.groups', function () {
  return Groups.find({
    _id: {
      $in: Roles.getGroupsForUser(this.userId)
    }
  });
});
```

I expect `Roles.GLOBAL_GROUP` to return _every_ group, wouldn't it? When I find someone in a particular group, it works fine.

```
// non global role user.
Roles.getGroupsForUser("someidhere");
["expected-group"]
```

**Comment by alanning** [comment]
In this case, `__global_roles__` is the group name of the global group, `internal` is the role that your user has in that group.

We could have returned `__global_roles__` when the user has a global role assigned but it did not seem like a useful thing to do because usually people care only about the groups that are using in their specific problem domain rather than the funky, hopefully non-conflicting key that we used for our global ones.

Does that help explain the reasoning there?

In your case, the term 'group' may be causing confusion.  Group in the sense that the `roles` package uses it indicates a distinct set of roles that should be independent from roles in any other groups the user may have.  So a user could have 'write' permission in 'group1' but only 'read' permission in 'group2'.  Think of groups as independent partitions when using the `roles` package.

**Comment by AlexFrazer** [comment]
That's more or less how I am using it, in a slightly odd way. There are groups such that `/group/:groupSlug` corresponds to a `Group` entity in Mongo. Then I use that ID as the "group", and add the roles for that group.
The problem is people who have "internal" on the GLOBAL_GROUP can view all groups and has all privileges. So it seems logically that someone with a role in the GLOBAL_GROUP technically has that role in every group, no?

**Comment by alanning** [comment]
> So it seems logically that someone with a role in the GLOBAL_GROUP
technically has that role in every group, no?

Yes, so if you did a `Roles.userIsInRoles(userId, "internal", "foo")` you'd
get true. Actually, you'd get true even without even needing to pass a
specific group.

But the call to `Roles.getGroupsForUser` wouldn't really make sense for it
to return "__global_roles__" as a result. In this case, "internal" is a
role/permission, not a group name.

**Comment by AlexFrazer** [comment]
Hm okay, here is an example of what I was thinking about. 

https://gist.github.com/AlexFrazer/1b531c85a07ac7db9153

Not sure if I am thinking about it right

**Comment by alanning** [comment]
Yep, that should work:

```
Roles.userIsInRole(idHuK, 'player', starcraftId)   // => true
Roles.userIsInRole(idSwifty, 'player', warcraftId)   // => true
Roles.userIsInRole(corvidId, 'player')   // => true
```

For your publish, I'd add a special-case for the global player option:

```
  // ... in publish games function
  if (Roles.userIsInRole(this.userId, 'player', Roles.GLOBAL_GROUP)) {
    return Games.find({})
  } else {
    // ...
  }
```

For our app, we have a special permission for these super-admin types and we just check for that.  I'd also recommend a separate field that just has the Games that the user has access to.  That way you can index on that field and do a very quick query on players by game if you need.  (Roles has "getUsersInRole" which could potentially accomplish the same thing but that's a very expensive query due to how roles internally stores the data on the user object.)

**Comment by AlexFrazer** [comment]
I see, that's what I ended up doing. Wasn't sure if this was appropriate for a PR. Thanks for the help!
