### ISSUE TITLE
Feature Request: Roles per user in more than one group

### ISSUE THREAD

**Issue by gentunian** [alanning/meteor-roles#117]
Some use cases may arise where you have a specific user, `John Doe`, in more than one group, `A-Team`, `MI-5`. The users may have the same role only in those groups, `manager`, and just one role in one group, `granadier`:

```
"roles" : {
  "A-Team" : [ "manager", "granadier" ],
  "MI-5" : [ "manage" ]
} 
```

`John Doe` manager role holds in both groups, `A-Team` and `MI-5`.

It would be nice to provide that functionality in `Roles.userIsInRole()` function.

I've created a fork and provided a simplified solution of how it could be done [here](https://github.com/gentunian/meteor-roles/commit/ee641e168c64466bf9fb3442cc0841e3be873037)

**Comment by gentunian** [comment]
Use-case code example:

```
var groups = Roles.getGroupsForUser(userId);
if (Roles.userIsInRole(userId, ['admin'], groups, 'all')) {
    // This user has the 'admin' role for the groups he/she belongs
}

// Retrieve the managers from the groups the users belongs to
users = _.pluck(Roles.getUsersInRole('manager', groups).fetch(), '_id');
```

**Comment by alanning** [comment]
Hi @gentunian, I'm having a bit of trouble understanding the use case.  Can you post what you are trying to accomplish in your actual app?

As far as I can tell, the goal is to be able to ensure that a user has a specific role in _all_ of a set of specified groups, right?  So if the user only has manager in one but not both, you want it to return false?

**Comment by gentunian** [comment]
Hey @alanning ,

Suppose your user belongs to more than one group. To know which group your user belongs, you do:
```
 var groups = Roles.getGroupsForUser(userId);
```

Now, if you have the need to check if a specific role holds in just one group: 
```
var groups = Roles.getGroupsForUser(userId);
var hasAdminRole = Roles.userIsInRole(userId, ['admin'], groups, 'any')
```

or in all groups: 
```
var groups = Roles.getGroupsForUser(userId);
var hasAdminRole = Roles.userIsInRole(userId, ['admin'], groups, 'all')
```

The first one could not provide you enough information but it is there to offer another option.

In my case, the last example will apply mostly, where I will provide to the administrator of the groups the ability to administer the users that are in those groups.

But more than a use-case, is the fact that the package allows you to have a user be in more than just one group. So it makes sense to me to be able to check the roles in all the groups the user belongs.

I hope to made the idea clear.
Cheers.

**Comment by alanning** [comment]
Thanks, that does help.  Could you expand a bit more on this part, please: "administrator of the groups can administer the users that are in those groups"?

So, for example, you have a super-admin who can manage both A-Team and MI-5.  You want to be able to show this super-admin a list of people who have admin permission in _both_ A-Team and MI-5?  This kind of goes against the intended use of groups as a way to separate permissions into independent "partitions", no?  I guess another way to put it is, why is it important for someone to know that a user has "admin" rights in _all_ the groups vs. just a specific group?

Thanks for working with me on this.  I want to make sure I understand the root goal/problem.

**Comment by gentunian** [comment]
I see. I understand that it could break your definition of partitions for the project. For me, is just one more level of _partitioning_ like a workaround more than a deep solution.

I work at Operations. This area is divided by _Linux_, _Windows_, _Networking_, _Security_, etc. Every area has its administrator, but also, _Operations_ has a manager that his access rights are above all. So, a way to provide that functionality would be using `GLOBAL_GROUP` or adding a **manager** role in those groups. That is, the manager manages all groups but the administrators manages only the groups they belong to. This could be done by adding another group called **operations** with a **manager** role, but by doing that your group schema has no relationship and you must ensure that groups in your application only apply to _Operations_ area. If you add another area, like _Support_, you can't follow this approach, just because the Operations manager does not manages Support.

The above is just an example. The idea of having the feature came also because you can have a user belong to more than one group (using `Roles.getGroupsForUser`). So, instead of checking a role for a specific group, it could be handy to check a role for the groups the user belongs to.

**Comment by gentunian** [comment]
Maybe a related issue is the possibility to know which group the user has a specific role. As I stated before, maybe all this conflicts with your definition of partition.

The fact that you don't know if a user belongs to more than one group and also that you don't know which group he belongs to, makes you write a more general approach for making specific publications or access-granted procedures.

If arises the case where you want to publish the list of users to the administrator of a group where those users are, you may find it quite complicated if the administrator is in another group with, possibly, another role. One may be tempted to get the groups where the user has a specific role. That would let you get all users in those groups. Of course this could be done by iterating the array `Roles.getGroupsForUser()` and check in each iteration `Roles.userIsInRole()` for each group and the role you want to get info from.

I was just thinking that all the overhead could be avoided with some modifications to the `API`, but as you said, could be a not-valid-effort considering that could break your definition of partition. For me is like a workaround for one more level of grouping.

**Comment by gentunian** [comment]
I won't extend more, but I wanted to leave a last hierarchy tree example:

```
-+= IT Department       (director role)
 |
 |---+= Support         (manager role)
 |   |---+= Events
 |   |---+= Equipment
 |
 |---+= Development     (manager role)
 |   |---+= Developers
 |   |---+= Analists
 |
 |---+= Operations      (manager role)
 |   |---+= Linux
 |   |---+= Windows
 |   |---+= Networking
```

Consider the example above. You could make a flat model by following this rule: All leaf are groups. Each node (and leaf) should have a role that identifies a user as a top level administrator. And, a user role for a higher level must be set in all the groups that are its branch.

Roles in the example could be: user, admin, manager, director.

For instance, the role **director** for a user must be set in all groups below the **IT Department** branch. The manager of Operations should have the role **manager** in all Linux, Windows and Networking groups, and so on...

I found that is the only way to establish a relationship. If you create a group for each node and leaf, you can't establish a relationship within groups. You don't know how they are related. You must hardcode the logic. 

This way, you will be agnostic of which group a user belongs. You just know that he is the **manager** of the groups so he could _manage_ each user in those groups.

Best regards,

**Comment by alanning** [comment]
Thanks, that is a great explanation.

I do think that the underlying issue of a hierarchy of groups/partitions is important.

For what its worth, at my own startup we use a hierarchy tree very similar to that in your comment.  As you described, we group by leaf and use the `GLOBAL_GROUP` to grant extra permissions across a range of groups.  We also have a higher-level Auth layer which handles specific business rules and can also grant access across groups.

Things like, "Users can modify this data if they have the role 'manager' in this group, OR if they have the 'regional-director' role and their region covers this group, OR ...".   I'm not sure, but I think that there will always be a need for that kind of Authorization layer.  But maybe its just a result of a lack of something in Roles...

We also include the hierarchy "path" in the group name.  Something like "Operations/Linux" instead of just "Linux".  Not sure but that may be a good candidate for a package that builds on top of roles and transparently supports this kind of hierarchy.  Speaking of which...

----

*Roles 2.0*

My ultimate goal for this package is for it to be the foundation for many different types of authorization structures.  I'm currently working on the design of Roles 2.0 which would ideally allow for other packages built on top of this one to provide this kind of group hierarchy.

With that in mind, I'd love for your help figuring out just what Roles 2.0 needs to do in order to be a good foundation.  Some areas I've identified so far are:

1) Restructure database schema to allow for indexes on groups or roles.

```
user: {
  roles: [
    {name: "Linux", roles: ["view", "manage"]},
    {name: "Windows", roles: ["view"]}
  ]
}
```

2) Expose the query object for further modification.  Also allow passing in of an existing query.  Something along the lines of #100

3) Provide pre and post hooks around each function which other packages can use to modify data or results.

```
// In GroupHierarchy package initialization code, something like...
Roles.addHook(Roles.userIsInRole, "pre.foo", GroupHierarchy.userIsInRolesWrapper)

// and ...
Roles.removeHook(Roles.userIsInRole, "foo")
```



If you're interested in working on a "Group Hierarchy" plugin, I'd love to work with you to make sure that the Roles 2.0 API gives you what you need to make it happen.

**Comment by gentunian** [comment]
I'm willing to help and contribute in any way I can. Are you interested in following ACL approach?

**Comment by alanning** [comment]
Great, thanks!  (And sorry for the late reply, I was traveling overseas and just got back home.)

Regarding ACL, I am interested in hearing more of your thoughts on it.  My impression is that meteor-roles does allow ACL of a sort...

`Roles.addUsersToRoles(bob, ['create', 'read'], 'myResourceId')`

The difference being that the actual "access control list" data is not stored in one big list keyed by 'myResourceId' but rather split out into each user's account.  For my own use case, this is more performant since our checks are generally based on the currently logged-in user rather than a collection of resources.

As we've discussed, one thing this package doesn't do is hierarchy.  So, if mapped to the ACL terminology, that means there's no way to make ACLs inherit the ACLs of their parents which is something most ACL implementations support.  This kind of gets to the heart of the issue you raised, I think...

What do you think?

**Comment by gentunian** [comment]
Hey Adrian, I was busy too :)

Yes, that was the issue that started the topic. I agree with you on performance based on the currently logged user. Also, Roles is doing his job OK in granting access to users that request a specific resource.

I used vaguely the term ACL, you are right. I'll back on this issue later!

**Comment by gentunian** [comment]
I'm back, finally.

Re-reading this and taking into account the groups implementation, I think that mixing both or trying to emulate ACL approach will be tedious. There are complex scenarios you may have in ACL that consider those will make this package a lot complex. For instance, you could have roles/permission for a user mixed in each level, so a proper inheritance implementation should be done.

I think that the final user should take those consideration into account instead from the base of this package. Do you agree with that?

**Comment by mitar** [comment]
With v2.0 I think there is a cleaner understanding between two things: hierarchy of roles and partitions. Reading this ticket seems like you are confusing/mixing those two things and this is why there are issues. So for what you have been describing I think that hierarchy of roles is more what you want. Groups (now partitions) do offer a concept of a global partition which means a role is applied to all groups/partitions.

Support for hierarchy of groups/partitions might be needed, but I am not sure if really has to be implemented in core of the package. If you have your hierarchy of groups you can always implement the check by traversing the list of all groups which apply inside that hierarchy. It might be less efficient though, because you would be doing multiple queries against the database. One solution is to use `getRolesForUser` with limited to wanted roles and then post-process returned roles manually to check for any complicated logic/relations between groups/partitions.

Please check v2.0 and give us feedback. I am closing this ticket for now until it is clearer what exactly is still missing in v2.0.
