### ISSUE TITLE
Enable permissions to set roles

### ISSUE THREAD

**Issue by jdmswong** [alanning/meteor-roles#121]
I can't find a way to set a new user's role before Accounts.validateNewUser() triggers.  Assuming this is the case, What's stopping any user with createUser privileges from arbitrarily setting roles on users they create, giving them all 'super-admin' or 'open-secrets' powers?

**Comment by alanning** [comment]
When you grant permissions, you need to check that the person doing the
granting has rights to give the permissions they are granting.

For example, your user with "createUser" role would also need to have the
"super-admin" role in order to give "super-admin" rights.

So this is something you should check for wherever you grant the
permissions.

**Comment by alanning** [comment]
Btw, there's an example of defining `validateNewUser` in the readme:  https://github.com/alanning/meteor-roles/#usage-examples


I'll close this issue for now but feel free to continue this thread if you would like more help.
