### ISSUE TITLE
isInRole & userIsInRole() not working

### ISSUE THREAD

**Issue by lookingcloudy** [alanning/meteor-roles#122]
I created users server side as per your docs:

    Meteor.startup(function () {
        var users = [
            {name:"brad",email:"brad@blah.org",roles:['admin']}
        ];
    
        isUser = function (username) {
            return Meteor.users.findOne({emails: {$elemMatch: {address: username}}})
        };
    
        _.each(users, function (user) {
            var id;
    
            if (!isUser(user.email)) {
                id = Accounts.createUser({
                    email: user.email,
                    password: "blah",
                    profile: { name: user.name }
                });
    
                if (user.roles.length > 0) {
                    // Need _id of existing user record so this call must come
                    // after `Accounts.createUser` or `Accounts.onCreate`
                    Roles.addUsersToRoles(id, user.roles, 'default-group');
                }
            }
    
        });
    })

This does not work:

    {{#if ifInRole 'admin'}}
        <a class="waves-effect waves-light btn">Stuff</a>
    {{else}}
        <p>Login required</p>
    {{/if}}

Nor does this work:

    Roles.userIsInRole(user, ['admin'])

**Comment by alanning** [comment]
Hi @lookingcloudy, because a group was specified when you added the role/permission, you must also use the group when checking to see if the user has that permission:

```
{{#if ifInRole 'admin' 'default-group'}}
    <a class="waves-effect waves-light btn">Stuff</a>
{{else}}
    <p>Login required</p>
{{/if}}
```
```
Roles.userIsInRole(user, 'admin', 'default-group')
```

If you want the permission to apply irrespective of groups, then use Roles.GLOBAL_GROUP as the group:

```
Roles.addUsersToRoles(id, user.roles, Roles.GLOBAL_GROUP)
```

I'll update the readme to hopefully be more clear on that.

--
Also, just fyi, in mongo you can avoid $elemMatch by changing your key like so:
`Meteor.users.findOne({'emails.address':'brad@blah.org'})`

**Comment by lookingcloudy** [comment]
Thanks!
