### ISSUE TITLE
Group names

### ISSUE THREAD

**Issue by aermler** [alanning/meteor-roles#126]
Hello, I have a quick question. In http://alanning.github.io/meteor-roles/classes/Roles.html#method_addUsersToRoles it says that:

> Group names can not start with '$' or numbers.

But if I want to use a group id as a group name, they sometimes start with a number. In  this issue you mention that using a group id as name is okay: https://github.com/alanning/meteor-roles/issues/38
I also tried it and it works. So is that limitation that it can't start with numbers outdated? Just want to make sure that I won't get problems with my application later. :)

**Comment by alanning** [comment]
Hi @aermler, roles uses the group name as an actual field name in mongodb.  MongoDB used to throw an error when field names started with a number but a quick check of the [latest docs](http://docs.mongodb.org/manual/reference/limits/#Restrictions-on-Field-Names) doesn't mention numbers anymore.  Since you confirmed it works, I'll update our docs.

Thanks!
