### ISSUE TITLE
Client-side security

### ISSUE THREAD

**Issue by Masuzu** [alanning/meteor-roles#138]
I just wanted to know if it is possible and if so, how to deny calls to `Roles.addUsersToRoles` from the client? Thank you in advance!

**Comment by alanning** [comment]
Client-side security is automatic by default.

In Meteor apps, only the `profile` field of the `Meteor.users` collection is editable from the client unless you explicitly grant access to other fields yourself.  Since Roles also uses `Meteor.users` to store permission information, client-side changes are also not permitted.

You can see this in action by trying to manually use `Roles.addUserstoRoles` from the browser console.  Log in as the normal user at [this example app](http://roles.meteor.com/) and try to add 'view-secrets' permission.  You'll see console error messages similar to 'access denied'.
