### ISSUE TITLE
!Roles.userIsInRole(Meteor.user(), ['admin']) not working as expected in firefox(42.0 for ubuntu).

### ISSUE THREAD

**Issue by piyushmahensaria** [alanning/meteor-roles#157]
I am trying to write a onBeforeAction in routing javascript file (name:common.js, it is placed in a folder common to server and client called libs), but the routing does not happen because,

In Firefox:
`!Roles.userIsInRole(Meteor.user(), ['admin'])` returns **true** (unexpected) during execution in **javascript (common.js)**, which I know because I used alert(), 
and if I execute `!Roles.userIsInRole(Meteor.user(), ['admin'])` in **browser console** itself, then it returns **false** (expected).
I even tried moving common.js to client side, the issue still prevails.

In Chrome:
I know this is a issue because, it executes perfectly in Chrome, and returns **false** in **browser console** and **common.js** (as expected, in any case, even if common.js is on clientside or in common folder).

Just in case it helps (code):
```
Router.route('/rolesadmin', {
        template: 'adminTemplate',
        onBeforeAction: function() {
            alert(!Roles.userIsInRole(Meteor.user(), ['admin']));
            if (Meteor.loggingIn()) {
                this.render(this.loadingTemplate);
            } else if(!Roles.userIsInRole(Meteor.user(), ['admin'])) {
                this.redirect('/');
            }
            else{
                this.next();
            }
        }
    });
```

**Comment by piyushmahensaria** [comment]
On trying out a little more, I figured, if I execute the command `!Roles.userIsInRole(Meteor.user(), ['admin'])` anywhere else on client side or in common folder, it performs as expected in firefox as well. Confused with the issue.

**Comment by mcoenca** [comment]
Same issue, had it on all browsers. Worked very well before. Not sure what to blame, i updated a lot of packages recently, maybe new router version, as it was only in the onBeforeAction that i got the issue

**Comment by alanning** [comment]
This sounds like a race condition between when the check is executing and when the data is available on the client.

I did a talk covering this at a recent DevShop NY; you can see a description of the sequence of events in my slides here:  http://slides.com/alanning55/a-pattern-for-flowrouter-auth/#/4

The only weird thing is that I thought `onBeforeAction` was reactive so I would expect the check to return false until the data got there but then return true once the route re-runs.

The best way to avoid these kinds of race conditions is to move the auth checks to your templates.  You can find examples of how to do this in these examples in this repo:

* https://github.com/alanning/meteor-roles/tree/master/examples/flow-router
* https://github.com/alanning/meteor-roles/tree/master/examples/flow-router-advanced

**Comment by alanning** [comment]
To follow up on this, my talk on FlowRouter Auth is now up on the Meteor YouTube channel:  https://www.youtube.com/watch?v=KK_ua6vxkP4

**Comment by sahanDissanayake** [comment]
@alanning , just watch your talk, still have issues with the 
React + Flow Router + Roles

For example here is a demo repo
https://kadira.io/blog/meteor/meteor-ssr-support-using-flow-router-and-react

And if I wanted to check if the current user is an admin before showing any todos. But still have the SSR working.. 

I tried template level and Router level, template level seems to be working with a quick flash of template change, and on the chrome console there is a checksum invalid error.

This is because on the server the data was not loaded so the server thinks the current user is not an admin. How to go about this issue please ?

**Comment by alanning** [comment]
Please put a minimal app that reproduces the problem up on github and I can
assist. The repo you linked does not have the roles package.

**Comment by sahanDissanayake** [comment]
yep for sure

**Comment by sahanDissanayake** [comment]
If you could clone this repo @alanning please,
https://github.com/sahanDissanayake/hello-react-meteor

you might see the server rendered html is different from the client html, so there is an error/waring on the console.

Let me know if you'd like any more input from myside.

**Comment by alanning** [comment]
Just to be sure, the problem you are trying to overcome is to avoid the
flash of regular user content for admin users, right?

**Comment by sahanDissanayake** [comment]
Yes, 

but also I wish to have the SSR render the initial page for the user, If admin then I render the list on the 
server and send it down to the client, if NOT admin then nothing at all..

**Comment by alanning** [comment]
You're "loading..." message is displayed whenever the user is not admin so that logic is incorrect.  Rather you should display "loading" while you are waiting for the roles subscription to complete.  The handle is stored here:  `Roles.subscription`.

As for the checksum, I don't know React or SSR so I'm afraid I can't be much help there.  I'd suggest making as minimal an app as you can and then add back pieces until you trigger the error.  Then you'll know what it is that is causing it and can debug from there.

**Comment by sahanDissanayake** [comment]
great! thanks for the tips.. I will handle it :+1: there is always a way around

**Comment by vuhrmeister** [comment]
I want to hook up on this topic. Sorry for reopen it …

@alanning, you wrote:

> The best way to avoid these kinds of race conditions is to move the auth checks to your templates. 

Well, I just discovered that this is not enough. Even when checking in a template's `onRendered` callback the user data is not always fetched (`userIsInRole()` => `false`, `Meteor.users.findOne()` => `undefined`). On my local machine this occurs quite rarely. But on our development server this is almost always the case.

As expected, wrapping this piece of code into `Tracker.autorun()` works, but this is definitely not the way to go.

I'm now wondering how should I solve that issue. Checking for roles is crucial. And false negative isn't better than the other way round.

Another idea I had was to write a dummy publication and then wait on it in the routers onBefore hook (I'm using iron router). That works, but also I don't really like that solution.

Is there anything nicer? Or did I missed something?

**Comment by adammoisa** [comment]
Running into this prob too. Solved it by calling method in route since it always works fine on server. Don't know if this is optimal though... anyway here's the method:

**Server**
```
'use strict';

import { check }  from 'meteor/check';

Meteor.methods({
  roleCheck(role, group) {
    check(role, Match.OneOf(String, [String]));
    check(group, String);

    return new Promise((resolve, reject) => {
      resolve(Roles.userIsInRole(this.userId, role, group))
    })
  }
})
```

**Router (client/both)**
```
function roleCheck(role, group) {
  return Meteor.callPromise('roleCheck', role, group)
  .then(res => res)
  .catch(e => {
     console.log(e);
     return false;
  });
}

FlowRouter.route('/', {
  async action() {
    const
      isAdmin = await roleCheck('admin', 'admins'),
      isUser  = await roleCheck('user', 'users'),
      redir   = Session.get('redirectOnLogin');

    Session.clear('redirectOnLogin');

    if      (isAdmin) FlowRouter.go(redir || '/admin')
    else if (isUser)  FlowRouter.go(redir || '/user')
    else              FlowRouter.go(redir || '/login')
  }
});
```

**Comment by alanning** [comment]
@adammoisa Careful with this, it is not recommended.  You should definitely not be doing roles checking in routing.  Rather, its best to move the checks into the templates themselves.

Display the requested template as soon as possible, but with a loading message.  Once subs are loaded, if action needs to be taken, redirect from template.  See my vid on FlowRouter Auth, linked above.

For a bit of background, one of the main reasons why Arunoda wrote FlowRouter when IronRouter already existed was to cut out these kind of performance issues.  IronRouter's design encouraged a lot of logic to take place before anything was shown to the client.  You didn't have to do it that way but most people did and it resulted in poor perceived performance.  With FlowRouter, he purposefully made it non-reactive so that it would be hard to shoot yourself in the foot that way.
