### ISSUE TITLE
Delayed access to 'roles' object

### ISSUE THREAD

**Issue by ffxsam** [alanning/meteor-roles#183]
I've encountered something confusing. I have the following code in my layout component:

```
  getMeteorData() {
    if (!Meteor.userId()) {
      // User logged out or their login timed out
      store.dispatch(userLoggedOut());
    }

    if (Meteor.user()) {
      console.info('Checking if user is L11 admin:', Meteor.user());
      if (!Roles.userIsInRole(Meteor.userId(), 'admin', 'L11')) {
        store.dispatch(userLostSuperPrivs()); // User is no longer L11 admin
      }
    }

    return {
      user: Meteor.user()
    }
  }
```

On my `console.info` call, it dumps out my user info, though the `roles` object is missing, so it bounces me out of the admin layout. Then if I go into the Chrome console and dump out `Meteor.user()`, I see the `roles` object.

Why is this happening? I had to fix it with the following:

```
if (Meteor.user() && Meteor.user().roles) {
  if (!Roles.userIsInRole(Meteor.userId(), 'admin', 'L11')) {
    store.dispatch(userLostSuperPrivs()); // User is no longer L11 admin
  }
}
```

Yet in the examples folder, I don't see any code that checks to make sure `Meteor.user().roles` exists before using the `userIsInRole` method.

**Comment by alanning** [comment]
I believe this is a race condition due to the roles data not being on the client when the first check is performed.  You can find a description of the sequence of events [here](http://slides.com/alanning55/a-pattern-for-flowrouter-auth/#/4) and a previous discussion of this issue [here](https://github.com/alanning/meteor-roles/issues/157).

Basically you just need to display some kind of "loading" message while you are waiting for the roles subscription to complete. The handle is stored here: `Roles.subscription`.

Good suggestion to add this to the example apps.  If you are interested, a PR would be a great way to contribute!  :-)

Closing this issue but feel free to continue the discussion or re-open if I haven't addressed the proper concern.
