### ISSUE TITLE
Package for npm?

### ISSUE THREAD

**Issue by ickyrr** [alanning/meteor-roles#202]
@alanning, Are you going to package this for npm as well? Just curious. Thanks!

**Comment by Slavrix** [comment]
+1, would love a response or a way to do this if someone has one.

Im building an app using the ionic-meteor with ionic CLI tutorial as a base, and this roles package if i can find a way to get it to work with it would be awsome.

**Comment by alanning** [comment]
Yes, we are working on an npm port for use in some Lambda functions but haven't put it into production yet.  Code will be published here soon:
https://github.com/alanning/roles-npm

Initial publish to github won't have tests since they haven't been ported yet but will get those up once those are complete.

Please note that v2 of meteor-roles is not ported yet.  V2 has better performance than v1 for some queries (the ones you can't index with v1) so if you haven't checked it out yet, make sure to check the https://github.com/alanning/meteor-roles/tree/v2.0 branch.

**Comment by mitar** [comment]
Hm, how does a NPM Meteor package depend on Meteor? If we would to release 2.0 as NPM package first, how can that Package get access to `Mongo.Collection` for example?

**Comment by alanning** [comment]
The npm version uses a constructor that accepts the users collection.  In a
meteor app, you'd pass in the raw Mongo collection.  Something like this:

Mongo.Collection.rawCollection

(Sorry, don't have specific example, on phone atm)

**Comment by mitar** [comment]
Hm, but that means that you go around Meteor's Mongo API which means that some hooks people might have on collections will not trigger. Probably then [redis oplog](https://github.com/cult-of-coders/redis-oplog) will also not work.

**Comment by alanning** [comment]
Yes, that sounds accurate.  Throws a wrench into trying to depend on the
npm version from the Meteor package.

Its still possible we can re-use the npm package from within the Meteor
package and maintain the benefits of both but the straight node version
will need to have to be a bit more flexible to handle the differences.
Things like a facade on the users collection to handle the difference in
call arguments between meteor and straight node db calls.  Haven't fully
fleshed it out because we don't have those alternate use cases (yet).

Off-topic but do you use redis oplog?  Are there any published performance
tests comparing it to the MongoDB implementation?

Adrian

**Comment by mitar** [comment]
I am not yet using redis oplog, but I am following its development.

**Comment by alanning** [comment]
The NPM Package is now published with all tests passing!

https://www.npmjs.com/package/@alanning/roles

Repo: https://github.com/alanning/roles-npm

At time of writing its based on Meteor Roles 1.2.15.  The NPM package will be kept in sync with Meteor Roles v1.  If someone else wants to port over Roles v2, that would be a big help.
