### ISSUE TITLE
Usage Example for Accounts-UI

### ISSUE THREAD

**Issue by centinel3** [alanning/meteor-roles#72]
I have implemented the meteor accounts-ui package and was wondering if you had any usage examples to show how to add a role to a new user sign up if you are using the accounts-ui package. Any help would be appreciated. I'm looking forward to using this package with my next project. thank you for your time. -Chris

**Comment by d4nyll** [comment]
In all your examples, you have implemented the `Accounts.createUser` method yourself server-side, which is perfect if I were to implement all the user creation myself. However, I'd like to use the `accounts-password` package (along with `accounts-ui`) to save me a lot of hassle.

But when I do, I can no longer assign roles on account creation since I do not know when `accounts-password` is done creating the user. The next best thing is to require email verification and run the `Roles.addUsersToRoles` method inside `Accounts.onEmailVerificationLink`.

Or this is what I am trying:

    Accounts.onCreateUser(function (options, user) {
    	if (options.profile) {
    		user.profile = options.profile;
    	}
    	user.roles = {__global_roles__: []};
    	return user;
    });

Inside the `onCreateUser` method, I am manually adding a `roles` property and inserting the key myself, before returning the `user` document to be inserted into the `users` collection. This works, but it it an acceptable hack in your opinion?

In either case, it would be nice to see an example where `meteor-roles` integrates with `accounts-password` and `accounts-ui`?

**Comment by alanning** [comment]
Hi Daniel,

I've found most people eventually need to make their own signup form and end up calling `Accounts.createUser` on the server.

But this has come up before so I've added an example of using `roles` with `accounts-ui`:  https://github.com/alanning/meteor-roles/tree/master/examples/rolesWithAccountsUI

In the example, I extended the `Roles` object with a new method `setRolesOnUserObj` which does the same thing as `Roles.setUserRoles` but adds them directly to the passed-in object instead of updating the database.

The existing `roles` methods expect you to have a user `_id` already and I'm leery of changing those to update just the object since if the `_id` is not found, the object would then have the roles but the database wouldn't.  I'll probably ask on the `meteor-talk` group and see whether people think its better to have a separate method or update the existing ones.

Hope this helps.

**Comment by d4nyll** [comment]
Dear Adrian,

Thank you for your time and help, the `setRolesOnUserObj` method works great. I don't understand the point you made in your last paragraph though. The `user` object passed into the `onCreateUser` method will ***always*** have an `_id`, and this will get written to the database.

Thanks once again!

**Comment by mtikmani** [comment]
Hi Alaning, 
Any chance Roles.setRolesOnUserObj  making it to roles package itself so that I don't have to keep a copy of the method.

**Comment by alanning** [comment]
Hi @mtikmani, yes I'll include something like `setRolesOnUserObj` in the next release of the package but I don't have an estimate on when that will be right now.  Sorry!  :-/

**Comment by weijian19391** [comment]
Hi Alanning
I've seen the example that you have done integrating roles with accounts-UI, but i still don't quite get how do we set the role of a user. For example, i would like to set the role of the user with _id = "xxxxxx" to 'admin',  how do i use that example to achieve this?

**Comment by alanning** [comment]
@weijian19391, if the user record already exists in the database then:

```
Roles.setUserRoles(userId, 'admin')
```
Source - http://alanning.github.io/meteor-roles/classes/Roles.html#method_setUserRoles

If the user record does not exist yet, such as in `Accounts.onCreateUser`, then:

```
  Accounts.onCreateUser(function (options, user) {
    Roles.setRolesOnUserObj(user, ['admin']);

    if (options.profile) {
      // include the user profile
      user.profile = options.profile
    }

    // other user object changes...
    // ...
    
    return user;
  });
```
Source - https://github.com/alanning/meteor-roles/blob/master/examples/rolesWithAccountsUI/server/startup.js#L6

**Comment by weijian19391** [comment]
@alanning Thanks for your help! I must have missed out the part about the case when user exist, i only have to the roles. Thanks!

**Comment by mitar** [comment]
I have removed `setRolesOnUserObj` in v2.0 branch in 484e08fc6afbc1fdbb2b63def25666b3d0159447 because it cannot really work with subroles.

One should use `postSignUpHook` from [useraccounts](https://github.com/meteor-useraccounts/core) package (a community version of accounts UI with many improvements). So instead of creating your own custom form you can use that package which then provides with the necessary hook.
