### ISSUE TITLE
How to remove a group from user?

### ISSUE THREAD

**Issue by Praxie** [alanning/meteor-roles#81]
If I remove all roles from some group it becomes an empty array.

**Comment by alanning** [comment]
That's expected behavior but you could wrap the `roles` remove function to
check for empty array and remove the group field in that case. But
typically you would have another field on the user object to handle
membership.

This is for two reasons:

1. It's nice to have membership separate from authorization so you can do
things like have users that are a part of a group but haven't been assigned
any permissions yet. An organization may have different people handling
user management and may want to send an invite and verify email before
granting access.

2. There's no good way to index the group in the roles field so for high
frequency queries you will get better performance from a separate field
that you can index.

Hope that helps,

Adrian

**Comment by Praxie** [comment]
@alanning, thanks for reply. Is it a good way to remove group field?
```javascript
// removeUsersFromRoles method
_.each(users, function(user) {
  Meteor.users.update({_id:user}, update);
  if (Roles.getRolesForUser(user, group).length === 0) {
    unset = {$unset: {}};
    unset.$unset['roles.'+group] = "";
    Meteor.users.update({_id:user}, unset);
  }
})
```

**Comment by alanning** [comment]
That would work on the client-side but not the server-side.  Also, to avoid having to maintain your own fork of `roles`, I would do something like:

```
var origRemove = Roles.removeUsersFromRoles;

Roles.removeUsersFromRoles = function (users, roles, group) {
  origRemove.call(this, users, roles, group);

  _.each(users, function (user) {
    var userId = "no-user",
        unset = {$unset: {}};

    if ("string" === typeof user) {
      userId = user;
    } else if ("object" === typeof user) {
      userId = user._id;
    }

    if (Roles.getRolesForUser(userId, group).length === 0) {
      unset.$unset['roles.' + group] = "";
      Meteor.users.update({_id: userId}, unset);
    }
  });
}
```

**Comment by Praxie** [comment]
Thank you, your solution works on server. Appreciate your help.
