### ISSUE TITLE
Query all users within a role on ANY group

### ISSUE THREAD

**Issue by afuggini** [alanning/meteor-roles#83]
I'm using organization names for groups and roles can be 'admin', 'provider', etc.

How can I return users with a specific role in ANY group/organization?

`Roles.getUsersInRole` without a group argument does not work for all groups.

**Comment by alanning** [comment]
Hi Ariel,

For global roles, such as "SUPPORT_PERSONNEL" or something you can use the [`Roles.GLOBAL_GROUP`](http://alanning.github.io/meteor-roles/classes/Roles.html#property_GLOBAL_GROUP) group which will always be checked by `userIsInRole`.

But I think to get what you really want you'll have to write your own query.  (This is not part of `roles` because the point of the groups is to partition the roles so that each group is independent.)

```
// WARNING: Untested!
function findUsersByRoleIndependentOfGroup (targetRole) {
  var users = Meteor.users.find({}, {fields: {roles: 1}}),
        userIds = []
  
  users.forEach(function (user) {
    _.each(user.roles, function (roles, group) {
      if (_.contains(roles, targetRole)) {
        userIds.push(user._id)
      }
    })
  })
  
  return userIds
}
```

**Comment by alanning** [comment]
I should also mention that doing such a query is very expensive and if you find you need to run it a lot you may want to reconsider your domain model and/or your use of `meteor-roles`.

**Comment by afuggini** [comment]
You are right. I have come to the same conclusion and hence I am reevaluating how I'm using roles. Thanks for your input!
