### ISSUE TITLE
Add tag/release for v1.2.13

### ISSUE THREAD

**Issue by meonkeys** [alanning/meteor-roles#89]
I don't think I can submit a PR for adding a tag, so I'm just filing this issue.

I see that v1.2.13 is from the `meteor-0.9.1` branch... if I'm using Meteor v1.0.3.2, which version of `alanning:roles` should I use?

**Comment by alanning** [comment]
Hi @meonkeys, roles v1.2.13 has been working with Meteor v1+ so you should be OK.

There's actually no functional difference between the master branch and the meteor-0.9.1 branch; just non-functional changes required to fix issues with the package system.  There were some very specific Meteor versions that broke the package system around 0.9 and 0.9.1 so I created the `meteor-0.9.1` branch rather than wait for everyone to update to the fixed Meteor version.

There is one [open issue](https://github.com/alanning/meteor-roles/issues/91) that seems specific to Meteor v1.0.3.1 or v1.0.3.2 but I'm having trouble reproducing it.  Once I can get a good reproduction I'll release a new version with a fix (assuming its an issue with roles).
