### ISSUE TITLE
Roles.getUsersInRoles security issue

### ISSUE THREAD

**Issue by davidsyoung** [alanning/meteor-roles#92]
Hi,

Not sure if I'm entirely right with this or not so bare with me. Roles.getUsersInRoles, if used from the server side in a publish function returns user objects WITH the services field.

Maybe it would be a good idea to omit the services field in the method.

Thank you for a great package.

Dave

**Comment by alanning** [comment]
Hi Dave,

Thanks for the comment.  I wouldn't classify this as a security issue since you still control what you publish.  But I do think its a great suggestion to be able to limit the fields that are returned by the function call.

Probably the best way to do this is to pass an `options` parameter as the 3rd param to [`getUsersInRoles`](http://alanning.github.io/meteor-roles/classes/Roles.html#method_getUsersInRole) and check for an `options.fields` object that we can pass on to Mongo.

Quick question, are you using groups?

**Comment by davidsyoung** [comment]
I agree Adrian, hardly a security issue just thought it wouldn't be a bad
idea.

Nope I'm not using groups! I like the options idea.

**Comment by alanning** [comment]
OK, since you aren't using groups, be sure to create an index on the `roles` field so that your getUsersInRoles function call doesn't do a complete table scan.

**Comment by davidsyoung** [comment]
Awesome. Thanks for the advice.

**Comment by alanning** [comment]
Just released v1.2.14 which adds an `options` param to [getUsersInRole](http://alanning.github.io/meteor-roles/classes/Roles.html#method_getUsersInRole).  The options param is passed directly through to the collection call so you can now limit the fields returned.
