### ISSUE TITLE
Running meteoer -test-packages causes dependency issue

### ISSUE THREAD

**Issue by robertpitt** [alanning/meteor-roles#95]
When running my tests where roles is a dependency of my package, I get the following error:

```
The package alanning:roles at 1.0.0 is incompatible with Meteor 0.9.0 or later. 
If a new, compatible version of this package exists, running 'meteor update' should cause you to update. 
```

Any ideas, Im currently running Meteor `1.0.5` with roles version `1.2.13`.

Regards

**Comment by alanning** [comment]
Hi Robert,

That's a bit strange; roles v1.2.13 is the right version.  I just tried using roles in a Meteor 1.0.5 app and no issues there so I'd guess that one of the packages your tests are using is pulling in an older version of roles.

Just to confirm, you aren't seeing any issues when running your main app, right?

To track this down, I'd try running your same test frameworks with a dummy app and adding the packages you are using one-at-a-time until the tests break.  Once we know which package is the culprit, we can see about getting the author to use a more recent version of roles.  (Assuming that's what the actual issue is, of course.)

**Comment by TimMikeladze** [comment]
@robertpitt Be sure that you're always explicitly defining the version of your dependent packages in your package.js file. If you don't mention the package number Meteor may not always use the same package versions when running the app vs running tests due to its internal logic when resolving packages versions.

**Comment by alanning** [comment]
Closing this issue for now. Please re-open if you'd still like help with this.
