### ISSUE TITLE
Roles.createRole permissions

### ISSUE THREAD

**Issue by boboci9** [alanning/meteor-roles#98]
Hi,
In addition to my issues in 1.) I also have several questions and I didn't find you on gitter so I will add them here :) 
1. I am trying to create an ui for the handling of the roles and permissions using your meteor-roles package but I seem to have entered in an issue with the createRoles. My user that I'm trying this code with is in roles: ['admin', 'owner', 'manage-users'] but when using Roles.createRole I get insert failed: Access denied error in the client console.
2. Do you know of any existing package that already has a UI for managing the roles and permissions?
3. Can you please tell me how the permissions work because I am working with reaction-core and I understand the roles come in the user collection but I can only see examples of permissions in the shop array which couldn't come from your package since Shops is a reaction core collection. I also read the docs attached to your package but I can't seem to figure out how the permissions for each role should work and where they should be added?
Thank you !!
Bogi

**Comment by alanning** [comment]
Hi Bogi,

Nice to hear you are considering `roles` for your project.  To keep things simpler, I'll answer each part separately:

1. The "Access denied" error you're seeing on the client side indicates that you haven't granted them access to the Roles collection.  *Not* granting access to clients is actually what I would recommend, though.  Rather, I'd advise doing the role creation server-side from a Meteor method so that you can better control who can do what.

2. I don't know of any specifically but [searching on Atmosphere](https://atmospherejs.com/packages/roles) shows a few.  You can also look at the Dependants section on the [roles Atmosphere page](https://atmospherejs.com/alanning/roles) to see which packages depend on `roles`.

3. [This section](https://github.com/alanning/meteor-roles#changes-to-default-meteor-behavior) of the Readme describes how the roles are actually stored on the user object in the database.  I'd also recommend checking out the [mini-pages](https://github.com/alanning/meteor-roles/tree/master/examples/mini-pages) example.  It uses a pre-cursor to iron-router but the `roles` part of it is still relevant.

Hope that helps!

**Comment by lionellei** [comment]
Hi, I will piggy back into this question, I have a slightly different concern. Once a role is created, any knowing user could go to the console and do Roles.addUserInRole to add oneself to the desire role. I have .allow for the Meteor.users collection, but the Roles.addUserInRole seem to bypass that, does the addUserInRole use a meteor method to modify the user's "roles" field? If that's the case, then we have no effective protection against user adding oneself to all the privileged roles.

**Comment by lionellei** [comment]
ok. false alarm. the problem or seemingly problem is that the Meteor.users.allow rule may get skipped some times (I don't know why), but having a complimentary Meteor.users.deny rule will fix it. thanks.
